In [1]:
import numpy as np

In [10]:
# Create an Array
a = np.array([2,1,3])
b = np.array([(1.5,2,3),(4,5,6)], dtype = float)
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]], dtype = float)

In [6]:
#Sorting 
a.sort()
a

array([1, 2, 3])

In [7]:
c.sort()
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ]]])

## Subsetting, Slicing, Indexing

Subsetting

In [9]:
#Select the element at the 2nd index
a[2]

3

In [11]:
#Select the element at row 1 column 2 (equivalent to b[1][2])
b[1,2]

6.0

Slicing

In [12]:
#Select items at index 0 and 1
a[0:2]

array([2, 1])

In [13]:
#Select items at rows 0 and 1 in column 1
b[0:2,1]

array([2., 5.])

In [14]:
#Select all items at row 0 (equivalent to b[0:1, :])
b[:1]

array([[1.5, 2. , 3. ]])

In [15]:
#Same as [1,:,:]
c[1,...]

array([[3., 2., 1.],
       [4., 5., 6.]])

In [16]:
#Reversed array a array([3, 2, 1])
a[: :-1]

array([3, 1, 2])

Boolean Indexing

In [17]:
#Select elements from a less than 2
a[a < 2]

array([1])

Fancy Indexing

In [18]:
#Select elements (1,0),(0,1),(1,2) and (0,0)
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [19]:
#Select a subset of the matrix’s rows and columns
b[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## Array Manipulation

Transposing Array

In [22]:
#Permute array dimensions
i = np.transpose(b)
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [23]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Changing Array Shape

In [25]:
#Flatten the array
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [26]:
g = a- b
#Reshape, but don’t change data
g.reshape(3,-2)

array([[ 0.5, -1. ],
       [ 0. , -2. ],
       [-4. , -3. ]])

Adding/Removing Elements

In [28]:
h = a.copy()
#Return a new array with shape (2,6)
h.resize((2,6))
h

array([[2, 1, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [29]:
#Append items to an array
np.append(h, g)

array([ 2. ,  1. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0.5, -1. ,  0. , -2. , -4. , -3. ])

In [33]:
#Insert items in an array 3 is index 5 is adding value
np.insert(a, 3, 5)

array([2, 1, 3, 5])

In [34]:
#Delete items from an array
np.delete(a,[1])

array([2, 3])

Combining Arrays

In [35]:
d = np.arange(10,25,5)
#Concatenate arrays
np.concatenate((a,d),axis=0)

array([ 2,  1,  3, 10, 15, 20])

In [36]:
#Stack arrays vertically (row-wise)
np.vstack((a,b))

array([[2. , 1. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [37]:
e = np.full((2,2),7)
f = np.eye(2)
#Stack arrays vertically (row-wise)
np.r_[e,f]

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [39]:
#Stack arrays horizontally (column-wise)
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [40]:
#Create stacked column-wise arrays
np.column_stack((a,d))

array([[ 2, 10],
       [ 1, 15],
       [ 3, 20]])

Splitting Arrays

In [42]:
#Split the array horizontally at the 3rd index
np.hsplit(a,3)

[array([2]), array([1]), array([3])]

In [43]:
#Split the array vertically at the 2nd index
np.vsplit(c,2)

[array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 1.],
         [4., 5., 6.]]])]