In [1]:
import numpy as np

## Array Mathematics

In [2]:
a = np.array([1,2,3])
b = np.array([(6,2,5),(2,6,4)])

Arithmatic Operations

In [4]:
# Subtraction
g = a - b
g

array([[-5,  0, -2],
       [-1, -4, -1]])

In [5]:
np.subtract(a,b)

array([[-5,  0, -2],
       [-1, -4, -1]])

In [6]:
# Addition
b + a 

array([[7, 4, 8],
       [3, 8, 7]])

In [7]:
np.add(b, a)

array([[7, 4, 8],
       [3, 8, 7]])

In [8]:
# Division
a / b

array([[0.16666667, 1.        , 0.6       ],
       [0.5       , 0.33333333, 0.75      ]])

In [10]:
np.divide(a,b)

array([[0.16666667, 1.        , 0.6       ],
       [0.5       , 0.33333333, 0.75      ]])

In [11]:
# Multiplication
a * b

array([[ 6,  4, 15],
       [ 2, 12, 12]])

In [12]:
np.multiply(a ,b)

array([[ 6,  4, 15],
       [ 2, 12, 12]])

In [13]:
#Exponentiation
np.exp(b)

array([[403.42879349,   7.3890561 , 148.4131591 ],
       [  7.3890561 , 403.42879349,  54.59815003]])

In [14]:
# Square root
np.sqrt(b)

array([[2.44948974, 1.41421356, 2.23606798],
       [1.41421356, 2.44948974, 2.        ]])

In [15]:
#Sines of an array
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [16]:
#Element-wise cosine
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [17]:
#Element-wise natural logarithm
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [18]:
f = np.eye(2)
e = np.full((2,2),7)
#Dot product
e.dot(f)

array([[7., 7.],
       [7., 7.]])

Comparison

In [19]:
# Element wise comparison
a == b

array([[False,  True, False],
       [False, False, False]])

In [20]:
# Element wise comparison
a < 2

array([ True, False, False])

In [21]:
# Array-wise comparison
np.array_equal(a ,b)

False

Aggregate Functions

In [22]:
# Array-wise operation
a.sum()

6

In [23]:
# Array-wise min value
a.min()

1

In [24]:
# Maximum value of an array row
b.max(axis = 0)

array([6, 6, 5])

In [25]:
# Cumulative sum of the elements
b.cumsum(axis=1)

array([[ 6,  8, 13],
       [ 2,  8, 12]], dtype=int32)

In [27]:
# Mean
a.mean()

2.0

In [29]:
#Standard deviation
np.std(b)

1.6749792701868151

## Copying Arrays

In [30]:
#Create a view of the array with the same data
h = a.view()
h

array([1, 2, 3])

In [31]:
#Create a copy of the array
j = np.copy(a)
j

array([1, 2, 3])

In [33]:
#Create a deep copy of the array
h = a.copy()
h

array([1, 2, 3])