In [3]:
import numpy as np

## Creating Arrays

In [5]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3),(4,5,6)], dtype = float)
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]], dtype = float)

Initial Placeholders

In [17]:
#Create an array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
# Create an array of ones
np.ones((2,3,4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [21]:
#Create an array of evenly spaced values (step value)
d = np.arange(10,25,5)
d

array([10, 15, 20])

In [22]:
#Create an array of evenly spaced values (number of samples)
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [23]:
# Create a constant array
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [24]:
# Create a 2X2 identity matrix
np.random.random((2,2))

array([[0.4629513 , 0.1953558 ],
       [0.343152  , 0.41664566]])

In [25]:
# Create an emty array
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

## I/O

Saving & Loading On Disk

In [27]:
np.save("my_array",a)
np.savez("array.npz",a,b)
np.load("my_array.npy")

array([1, 2, 3])

## Asking For Help

In [28]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


## Inspecting Array

In [32]:
# Array dimantions
a.shape

(3,)

In [33]:
c.shape

(2, 2, 3)

In [34]:
# Lenght of the array
len(a)

3

In [35]:
# Number of array dimantions
b.ndim 

2

In [36]:
# Number of array elements
c.size

12

In [37]:
# Data type of Array element
b.dtype

dtype('float64')

In [38]:
# name of data type
b.dtype.name

'float64'

In [39]:
# Convert an array to a diffirent type
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

## Data Types

In [40]:
#Signed 64-bit integer types
np.int64

numpy.int64

In [41]:
#Standard double-precision floating point
np.float32

numpy.float32

In [44]:
#Complex numbers represented by 128 floats
np.complex64

numpy.complex64

In [45]:
#Boolean type storing TRUE and FALSE values
np.bool_

numpy.bool_

In [46]:
#Python object type
np.object0

numpy.object_

In [47]:
#Fixed-length string type
np.string_

numpy.bytes_

In [48]:
#Fixed-length unicode type
np.unicode_

numpy.str_